export const countries = [
  { country: "Excessive sweating" },
  { country: "Abnormal hair loss" },
  { country: "Sudden and severe back pain" },
  { country: "Difficulty or pain during sexual activity" },
  { country: "Changes in bowel color" },
  { country: "Abnormal breath odor" },
  { country: "Persistent bad taste in the mouth" },
  { country: "Nosebleeds that are difficult to stop" },
  { country: "Rapid or irregular heartbeat" },
  { country: "Difficulty starting or stopping urination" },
  { country: "Persistent bloating" },
  { country: "Changes in appetite" },
  { country: "Sudden and severe abdominal pain" },
  { country: "Double vision or other vision changes" },
  { country: "Feeling of a lump in the breast or testicle" },
  { country: "Unexplained irritability" },
  { country: "Persistent cough with blood-streaked sputum" },
  { country: "Swollen or painful joints" },
  { country: "Sudden onset of confusion" },
  { country: "Abnormal eye discharge" },
  { country: "Sudden or severe tooth pain" },
  { country: "Persistent nasal congestion" },
  { country: "Difficulty opening or closing the mouth" },
  { country: "Sudden loss of balance or coordination" },
  { country: "Unexplained weakness or paralysis" },
  { country: "Changes in fingernail or toenail texture" },
  { country: "Abnormal body odor" },
  { country: "Persistent indigestion" },
  { country: "Difficulty maintaining an erection" },
  { country: "Persistent itchy skin" },
  { country: "Unexplained bruising or bleeding" },
  { country: "Changes in handwriting" },
  { country: "Sudden sensitivity to light" },
  { country: "Pain or discomfort during urination" },
  { country: "Swelling or pain in the testicles" },
  { country: "Excessive gas or belching" },
  { country: "Unexplained anxiety or panic attacks" },
  { country: "Difficulty expressing thoughts verbally" },
  { country: "Persistent sensitivity to cold or heat" },
  { country: "Abnormal vaginal bleeding" },
  { country: "Sudden loss of taste or smell" },
  { country: "Persistent numbness or tingling in extremities" },
  { country: "Sudden onset of chest pain" },
  { country: "Difficulty bending or straightening a joint" },
  { country: "Abnormal curvature of the spine" },
  { country: "Sudden mood swings" },
  { country: "Excessive thirst with frequent urination" },
  { country: "Sudden onset of abdominal distension" },
  { country: "Changes in skin texture or thickness" },
  { country: "Unexplained weight gain" },
  { country: "Persistent cough" },
  { country: "High fever" },
  { country: "Severe headache" },
  { country: "Persistent fatigue" },
  { country: "Shortness of breath" },
  { country: "Chest pain" },
  { country: "Unexplained weight loss" },
  { country: "Difficulty swallowing" },
  { country: "Chronic pain" },
  { country: "Abdominal pain" },
  { country: "Nausea and vomiting" },
  { country: "Persistent diarrhea" },
  { country: "Blood in stool or urine" },
  { country: "Frequent urination" },
  { country: "Changes in bowel habits" },
  { country: "Joint pain or stiffness" },
  { country: "Muscle weakness" },
  { country: "Dizziness or lightheadedness" },
  { country: "Vision changes" },
  { country: "Hearing loss" },
  { country: "Skin rash or unusual skin changes" },
  { country: "Swelling in the limbs" },
  { country: "Difficulty sleeping" },
  { country: "Excessive thirst or hunger" },
  { country: "Mood swings" },
  { country: "Memory loss" },
  { country: "Difficulty concentrating" },
  { country: "Frequent headaches" },
  { country: "Changes in menstrual cycle" },
  { country: "Persistent coughing up of blood" },
  { country: "Frequent infections" },
  { country: "Bruising easily" },
  { country: "Tremors or involuntary movements" },
  { country: "Swollen lymph nodes" },
  { country: "Night sweats" },
  { country: "Feeling of a lump in the throat" },
  { country: "Changes in voice" },
  { country: "Persistent heartburn" },
  { country: "Allergic reactions" },
  { country: "Persistent sore throat" },
  { country: "Abnormal bleeding" },
  { country: "Bowel incontinence" },
  { country: "Persistent hiccups" },
  { country: "Skin discoloration or jaundice" },
  { country: "Changes in fingernails or toenails" },
  { country: "Tingling or numbness" },
  { country: "Balance problems" },
  { country: "Unexplained fevers" },
  { country: "Loss of appetite" },
  { country: "Unusual or severe reaction to medication" },
];
